mterwill/office-hours-help-queue

app/assets/javascripts/components/course_queue.js.jsx
app/assets/javascripts/components/course_queue_client_action_handler.js
app/assets/javascripts/components/instructor_message.js.jsx
app/channels/queue_channel.rb
app/controllers/course_queues_controller.rb
app/models/course_queue.rb
app/views/course_queues/instructor_message.json.jbuilder
config/routes.rb
db/migrate/20170424200546_add_instructor_to_course_queue.rb
db/schema.rb

This feature adds the ability for instructors to create and save a message at the top of a course queue. Instructors can choose to broadcast the message to everyone on the queue as well as have it displayed on the top of the queue, or just post their message silently. This closes #86. 
**Note**: the gif recording software didn't record with the best resolution. There are some graphical artifacts in the gifs that aren't present in the actual build
- Ability to broadcast message to all students on the queue (using incognito on the right window, so I couldn't opt in for the notifications instead of alert popups)
- Display message at the top of all queues
- Clears the message and does not display the message info to students when all instructors are offline
- Follows with the responsive …

Instructor can display and broadcast message to queue

---

app/assets/javascripts/components/instructor_message.js.jsx
app/assets/javascripts/components/message.js.jsx
app/assets/stylesheets/scaffold.css

Previously, messages would discard newline characters and just display them as a
space. Now, newlines are acknowledged and allow for prettier formatted messages. Although newlines are most affected by this, the new CSS affects whitespace in general.
**Previously:**
**Now:**
Closes #104

Allow messages to display newlines

---

app/views/layouts/application.html.erb

For some reason Chrome wants to translate our pages from Catalan.

Specify language

---

app/models/course.rb
test/models/course_test.rb

A course without any queues is useless, and the UI looks strange without one too.

Create default queue with new course

---

app/views/courses/_courses.html.erb

Just added a queue entry for a non-course that doesn't have a long name, and so shouldn't get a colon after the short name. The long name is not required and is not used anywhere else that I could find.

Don't display colon if long name is empty

---

app/assets/javascripts/components/course_queue.js.jsx

Make the message more obvious that it is a broadcast to the queue, rather than a
personal message to someone specific on the queue.
Closes #114.

Update broadcast message to make it less personal

---

app/channels/queue_channel.rb

Closes #115.
I believe the missing quotation marks didn't allow the instructor message to be propagated via Action Cable. Without the quotation marks, the application behaves as described in issue #115. After adding the quotation marks, updates to the instructor message on save and broadcast work properly most of the time. When testing locally, occasionally updates to the instructor message (as well as other actions like enqueuing a new request, or going offline) will not propagate. This doesn't seem to be a problem with this specific feature (due to it affecting other actions not related to this one). I believe @mterwill and I discussed this to be a problem with the development setup.

Add missing quotation marks

---

app/assets/javascripts/components/course_queue.js.jsx
app/assets/javascripts/components/queue_closed_message.js.jsx
app/controllers/admin/course_queues_controller.rb
app/models/course_queue.rb
app/views/admin/course_queues/_form.html.erb
app/views/admin/courses/_queues.html.erb
app/views/course_queues/show.html.erb
db/migrate/20181005025605_add_group_exclusive.rb
db/schema.rb

eecs.help already has a [group mode][] that allows instructors to upload a comma and newline delimited list of students. When group mode is on for a queue, it restricts the number of simultaneous requests per group to 1. For example, the following would create two groups, each with three members:
```
bob@umich.edu,mary@umich.edu,sue@umich.edu
fred@umich.edu,randy@umich.edu,diane@umich.edu
```
However, if `sarah@umich.edu` came around, they would still be allowed to enqueue as they are not in any group. This was a design choice to allow students who may not have made it on the initial roster to  enqueue.
This PR adds "exclusive mode," which, when enabled, prevents users who are not listed in _any_ group for the current course from enqueueing. (e.g. `sarah@umich.edu`)
Note that exclusive …

Add exclusive mode

---

app/models/course_queue.rb

Prevents a student from being on multiple queues for the same course.
Doesn't handle on the frontend too well. Just doesn't submit the request. Better would be provide an error to the user that they are already in another queue. 
Alternatively, if they request being on a new queue, we could drop them from all other queues?

Implement not allowing multiple queue joins #116

---

app/assets/javascripts/components/request.js.jsx
app/controllers/settings_controller.rb
app/models/user.rb
app/views/courses/index.html.erb
app/views/settings/edit.html.erb
config/routes.rb
db/migrate/20191110210519_add_nickname.rb
db/schema.rb

This feature was requested in #138. Because we pull the names from Google, there's no way for a user to change their display name.
This adds a 'Settings' page and corresponding link for users to edit settings specific to their account. Adding a nickname is the only thing on this page as of now.
If a user has a nickname, it will show up in parenthesis next to their official name:

Add ability for users to set their own nickname

---

app/assets/javascripts/components/course_queue.js.jsx
app/channels/queue_channel.rb
app/models/course_queue.rb
test/models/course_queue_test.rb

These exceptions, previously uncaught, would not indicate any error on the client side, leading to a confusing behavior where requesting for help would appear to be broken. This provides some indication to the client of the issue.
Relates to #140.

Surface errors from invalid requests

---

app/assets/javascripts/components/course_queue.js.jsx
app/views/layouts/application.html.erb

This PR addresses the enhancement requested by issue #131 , and was made with Ram Natla (@ramnatla). If the logged-in user is currently on the queue, the title of the page is updated to show their position: "(#2) Office Hours Help Queue". If the logged-in user is not on the queue, the title will display the total number of people on the queue. For example, if 20 people were on the queue, the title will display: "(20) Office Hours Help Queue". 
To implement this, any time the queue receives an update, the title of the page was dynamically changed. 
We would appreciate any and all feedback on this PR!

Adding enhancement #131 - Student title vs. Instructor title 

---

docker-compose.yml
script/migrate
script/wait-for-it.sh

If the database container is not ready when running migrations, they fail with:
```
Creating office-hours-help-queue_db_1 ... done
rake aborted!
Mysql2::Error: Can't connect to MySQL server on 'db' (115)
```
Add a helper script, [vishnubob/wait-for-it](https://github.com/vishnubob/wait-for-it/), as recommended by [docker-compose's help page](https://docs.docker.com/compose/startup-order/) to ensure the database is ready before kicking off migrations and starting the web server.

Wait for db to be available before running migrations

---

app/channels/queue_channel.rb
app/controllers/admin/course_queues_controller.rb
app/helpers/course_queues_helper.rb
app/views/admin/course_queues/_form.html.erb
app/views/admin/courses/_queues.html.erb
app/views/course_queues/outstanding_requests.json.jbuilder
db/migrate/20200312232645_add_hide_details_option.rb
db/schema.rb
test/fixtures/course_queues.yml
test/fixtures/users.yml
test/helpers/course_queues_helper_test.rb

#157 outlines a need to hide location/description details from students. There are a couple of long-standing issues (#55, #69) that outline a similar class of problem. There are two places where we transmit request data:
1) on initial page load, when a user fetches outstanding requests
2) via WebSocket, as events stream in
Any information hiding should be done on the server-side in both of these places. This is complicated by the fact that we want to show different users different information:
* The current user should always see their own request details.
* Students should not see other students request details if private mode is on.
* Instructors should always see all request details.
This PR implements a "private mode" toggleable on a per-queue basis that hides location and description …

Add option to hide details from other students

---

app/assets/javascripts/components/course_queue.js.jsx
app/channels/queue_channel.rb
app/helpers/course_queues_helper.rb

Currently, new requests are naively appended to the request list in the order that they are received. This PR serializes the canonical queue order and sorts the frontend accordingly.
Cherry picked from #136 for #148.
cc @MiloATH

Pass queue order to frontend when new requests are received

---

app/helpers/course_queues_helper.rb
test/fixtures/course_groups.yml
test/fixtures/course_queues.yml
test/helpers/course_queues_helper_test.rb

If group mode is on, students should be able to see the details of
requests in the same group.
Fixes #163

Update private mode to respect course groups

---

app/controllers/sessions_controller.rb

#180 upgraded to Rails 5.1. Login is currently broken as direct access to `env` was removed in Rails 5.1. I did not catch this issue in testing as I was already logged in.
```
undefined local variable or method `env' for #<SessionsController:0x00000000021a8ea0>
```

env was removed in Rails 5.1

---

config/environments/development.rb
config/environments/production.rb
config/initializers/deprecation_warnings.rb

To ease the process of upgrading Rails, notify Bugsnag on deprecated use in prod, and raise an exception in dev.

Notify or raise deprecation warnings

---

Gemfile
Gemfile.lock

Include new gems required for deployment. Was previously failing with:
/usr/local/bundle/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded': OpenSSH keys only supported if ED25519 is available (NotImplementedError)
net-ssh requires the following gems for ed25519 support:
* ed25519 (>= 1.2, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information.

Add gems required for deployment

---

README.md
config/environments/development.rb
config/initializers/omniauth.rb

Google is phasing out non-localhost plaintext HTTP redirect URIs for
OAuth2. See https://developers.google.com/identity/protocols/oauth2/policies#secure-response-handling.

Update dev redirect URL

---

app/views/admin/courses/_recent_request_stats.html.erb

This pull request implements the functionality of #82.
Time strings have been switched to display in EDT (Eastern Time) from UTC, as well as being displayed in a more readable format.
Attempting to have the time displayed in the user's local timezone via the ruby ".localtime" function always resulted in UTC being displayed, so we set it to display in EDT as a compromise.
Original Format:
New Format:

Pretty Print Timestamps in Statistics Page

---

app/channels/queue_channel.rb
app/controllers/admin/course_queues_controller.rb
app/models/course_queue.rb
app/views/admin/course_queues/_form.html.erb
app/views/admin/courses/_queues.html.erb
app/views/admin/courses/show.html.erb
db/migrate/20220519123402_jitter.rb
db/schema.rb
test/fixtures/course_queues.yml
test/models/course_queue_test.rb

There have been many reports over the years of students who script clicking of 'request help' so they land on the top of the queue when it first opens. Those without are left at the bottom of the queue, potentially waiting hours for help.
This adds an opt-in feature to scramble the request timestamp by +/- 10 seconds during the first minute a queue is open. It is:
* implemented entirely server-side, hopefully minimizing gameability
* automatic when enabled, so instructors can set it and forget it
* more-or-less transparent to students, though they may notice their
queue position change during the first minute
Hopefully this is enough to remove the edge for those using scripts and level the field. I marked the toggle as 'beta'; we can iterate on the approach depending on what instructors …

Optionally add jitter to initial requests

---

app/assets/javascripts/components/labeled_item.js.jsx

Before:
After:
Still does not parse text for links (unless it starts with a link) but at least we're no longer hiding user input.
Closes #206

Wrap, rather than truncate location/description

---

db/migrate/20230906154201_increase_avatar_url_length.rb
db/schema.rb

It appears that Google started sending longer URLs again.

Increase length of avatar_url column
